name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    strategy:
      matrix:
        include:
#          - image: crunchy-postgres
#            tag: centos8-12.6-4.6.2
#            share_path: /usr/pgsql-12/share
          - image: crunchy-postgres-ha
            tag: centos8-12.6-4.6.2
            share_path: /usr/pgsql-12/share
#          - image: crunchy-postgres-gis
#            tag: centos8-12.6-3.0-4.6.2
#            share_path: /usr/pgsql-12/share
#          - image: crunchy-postgres-gis-ha
#            tag: centos8-12.6-3.0-4.6.2
#            share_path: /usr/pgsql-12/share

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: |
            CRUNCYDATA_POSTGRES_IMAGE=${{ matrix.image }}
            CRUNCYDATA_POSTGRES_TAG=${{ matrix.tag }}
            SHARE_PATH=${{ matrix.share_path }}
          tags: dteamdev/${{ matrix.image }}-ukrainian:${{ matrix.tag }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Update repo description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: dteamdev/${{ matrix.image }}-ukrainian